AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: some description

Resources:
  ## Async Hello world lambda
  AsyncHelloWorldLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      FunctionName: AsyncHelloWorldLambda
      MemorySize: 512
      ## This path to lambda to invoke
      Handler: org.example.lambda.AsyncHelloWorldLambda::handler
      CodeUri: target/lambda.jar
  ## Sync Hello world lambda
  RequestResponseHelloWorldLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      FunctionName: RequestResponseHelloWorldLambda
      MemorySize: 512
      ## This path to lambda to invoke
      Handler: org.example.lambda.RequestResponseHelloWorldLambda::handler
      CodeUri: target/lambda.jar
  ## Sync lambda with boolean primitives
  RequestResponseBooleanLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      FunctionName: RequestResponseBooleanLambda
      MemorySize: 512
      ## This path to lambda to invoke
      Handler: org.example.lambda.RequestResponsePrimitivesLambda::handlerBoolean
      CodeUri: target/lambda.jar
  ## Sync lambda with int primitives
  RequestResponseIntLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      FunctionName: RequestResponseIntLambda
      MemorySize: 512
      ## This path to lambda to invoke
      Handler: org.example.lambda.RequestResponsePrimitivesLambda::handlerInt
      CodeUri: target/lambda.jar
  ## Sync lambda with Integer
  RequestResponseIntegerLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      FunctionName: RequestResponseIntegerLambda
      MemorySize: 512
      ## This path to lambda to invoke
      Handler: org.example.lambda.RequestResponsePrimitivesLambda::handlerInteger
      CodeUri: target/lambda.jar
  RequestResponseListLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      FunctionName: RequestResponseListLambda
      MemorySize: 512
      ## This path to lambda to invoke
      Handler: org.example.lambda.ListMapLambda::handlerList
      CodeUri: target/lambda.jar
  RequestResponseMapLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      FunctionName: RequestResponseMapLambda
      MemorySize: 512
      ## This path to lambda to invoke
      Handler: org.example.lambda.ListMapLambda::handlerMap
      CodeUri: target/lambda.jar
  RequestResponseListOfMapsLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      FunctionName: RequestResponseListOfMapsLambda
      MemorySize: 512
      ## This path to lambda to invoke
      Handler: org.example.lambda.ListMapLambda::handlerNestedCollection
      CodeUri: target/lambda.jar
  RequestResponsePojoLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      FunctionName: RequestResponsePojoLambda
      MemorySize: 512
      ## This path to lambda to invoke
      Handler: org.example.pojolambda.PojoLambda::handlerPojo
      CodeUri: target/lambda.jar
  RequestResponseStreamLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      FunctionName: RequestResponseStreamLambda
      MemorySize: 512
      ## This path to lambda to invoke
      Handler: org.example.lambda.StreamLambda::handlerStream
      CodeUri: target/lambda.jar
  ## Lambda with timeout
  TimeoutLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TimeoutLambda
      Timeout: 2 # 2s
      Runtime: java11
      MemorySize: 512 # Mb
      Handler: org.example.lambda.TimeoutLambda::handler
      CodeUri: target/lambda.jar
