AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: some description

Resources:
  ## Async Hello world lambda
  AsyncHelloWorldLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      FunctionName: AsyncHelloWorldLambda
      MemorySize: 512
      ## This path to lambda to invoke
      Handler: org.example.lambda.AsyncHelloWorldLambda::handler
      CodeUri: target/lambda.jar
  ## Async Hello world lambda
  RequestResponseHelloWorldLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      FunctionName: RequestResponseHelloWorldLambda
      MemorySize: 512
      ## This path to lambda to invoke
      Handler: org.example.lambda.RequestResponseHelloWorldLambda::handler
      CodeUri: target/lambda.jar
  ## Lambda with timeout
  TimeoutLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TimeoutLambda
      Timeout: 2 # 2s
      Runtime: java11
      MemorySize: 512 # Mb
      Handler: org.example.lambda.TimeoutLambda::handler
      CodeUri: target/lambda.jar
